name: igsismani
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - pip
  - obspy
  - numpy
  - pandas
  - scipy
  - requests
  - pillow
  - opencv
  - plotly
  - manim
  - moviepy
  - ffmpeg
  - fastapi
  - uvicorn
  - python-multipart
  - pytz
  - conda-pack
  - pytest

