name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: igsismani
          environment-file: environment.yml
          auto-activate-base: false
          
      - name: Check runner
        run: |
          hostname
          whoami
          pwd

      - name: Run tests
        shell: bash -el {0}
        run: |
          python -m pytest -v
